###Сброс пароля

POST localhost:8080/forgot?email=smirnovpa77@yandex.ru
Content-Type: application/json

###Обновление пароля
POST localhost:8080/reset?token=ecc8b5c3-ccd0-4183-b47d-3d2e2f8fbfaa
Content-Type: application/json

{
  "password": "password123"
}
