###Сброс пароля

POST localhost:8080/forgot
Content-Type: application/json

{
  "email": "smirnovpa77@yandex.ru"
}

###Обновление пароля
POST localhost:8080/reset?token=938bb182-07eb-47e1-8401-f00bd7a09719
Content-Type: application/json

{
  "password": "password123"
}
